server:
  port: 8090

dubbo:
  registry:
    address: nacos://localhost:8848
  application:
    name: com.wanglei.myapi.provider

spring:
  application:
    name: MyApi-gateway
  cloud:
    gateway:
      default-filters:
        - AddResponseHeader=source, yupi
      routes:
        - id: api_route
          uri: http://localhost:8123
          predicates:
            - Path=/api/**

